# Generated by Django 3.1.4 on 2021-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookDescription',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AddField(
            model_name='book',
            name='bookPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
