# Generated by Django 3.1.5 on 2021-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210108_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(default='1', upload_to='media/'),
            preserve_default=False,
        ),
    ]
