# Generated by Django 3.1.5 on 2021-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(upload_to='media/media/'),
        ),
    ]
