# Generated by Django 3.1.5 on 2021-02-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210212_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookCover',
        ),
    ]
